### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by RTOBIA** [RTOBIA/LSOBIA#1]
![labeloutput_0_0](https://cloud.githubusercontent.com/assets/26165185/24074026/b7a80e6e-0c01-11e7-8d09-a98da0f14157.jpg)

**Comment by RTOBIA** [comment]
![input](https://cloud.githubusercontent.com/assets/26165185/24074238/073c72b4-0c05-11e7-82e3-497a28d10db1.png)

![labeloutput_0_0](https://cloud.githubusercontent.com/assets/26165185/24074247/3a061d62-0c05-11e7-9266-31a16d203afc.jpg)

**Comment by Julien-Osman** [comment]
Let's use a "figures" directory!
